name: Build and Deploy

on:
  push:
    branches: [main]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        with:
          ref: main
      - name: Commit and push into the main branch
        run: |
          date >> date.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add --all
          git commit -m "site build"
          git push
